apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:latest
        ports:
        - containerPort: 80
        env:
        - name: MEDIAWIKI_DB_HOST
          value: mysql
        - name: MEDIAWIKI_DB_NAME
          value: mediawiki
        - name: MEDIAWIKI_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MEDIAWIKI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

